version: '3'

services:
  web:
    image: kinoglazprusia/no-plan:v1.0.0
    ports:
      - 80:80
    depends_on:
      - db
 
  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kinoglaz
      - MYSQL_DATABASE=no_plan_db
      - MYSQL_USER=noplanuser
      - MYSQL_PASSWORD=noplanuser

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=kinoglaz