version: '3'

services:
  web:
    image: kinoglazprusia/no-plan:v1.0.1
    ports:
      - 85:80
    depends_on:
      - db
    restart: always
 
  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql # Seleccionar el volumen en el que se guardará la base de datos y después hacer un import con phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=kinoglaz
      - MYSQL_DATABASE=no_plan_db
      - MYSQL_USER=noplanuser
      - MYSQL_PASSWORD=noplanuser
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=kinoglaz
    restart: always
    
    